name: Publish to npm

on:
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check if version already on npm
        id: check
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VER=$(node -p "require('./package.json').version")
          if npm view "$PKG_NAME@$PKG_VER" version >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Version $PKG_NAME@$PKG_VER already exists on npm."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Version $PKG_NAME@$PKG_VER not found on npm. Will publish."
          fi

      - name: Publish
        if: steps.check.outputs.exists == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
